apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opendismissal.fullname" . }}
  labels:
    {{- include "opendismissal.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "opendismissal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opendismissal.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opendismissal.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.initDb.enabled }}
      initContainers:
        - name: wait-for-db
          image: {{ .Values.initDb.image }}
          command: ["sh", "-c", {{ printf "%q" .Values.initDb.command }}]
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_PORT
          {{- with .Values.initDb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ include "opendismissal.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: DEBUG
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: ALLOWED_HOSTS
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_PORT
            - name: POSTGRES_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: POSTGRES_SSLMODE
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=$(POSTGRES_SSLMODE)"
            - name: TIME_ZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: TIME_ZONE
            - name: USE_TZ
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: USE_TZ
            - name: SESSION_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_ENGINE
            - name: SESSION_COOKIE_AGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_COOKIE_AGE
            - name: SESSION_COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_COOKIE_SECURE
            - name: SESSION_COOKIE_HTTPONLY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_COOKIE_HTTPONLY
            - name: SESSION_COOKIE_SAMESITE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_COOKIE_SAMESITE
            - name: SESSION_SAVE_EVERY_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SESSION_SAVE_EVERY_REQUEST
            - name: STATIC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: STATIC_URL
            - name: STATIC_ROOT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: STATIC_ROOT
            - name: STATICFILES_STORAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: STATICFILES_STORAGE
            - name: SECURE_BROWSER_XSS_FILTER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_BROWSER_XSS_FILTER
            - name: SECURE_CONTENT_TYPE_NOSNIFF
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_CONTENT_TYPE_NOSNIFF
            - name: SECURE_HSTS_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_HSTS_SECONDS
            - name: SECURE_HSTS_INCLUDE_SUBDOMAINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_HSTS_INCLUDE_SUBDOMAINS
            - name: SECURE_HSTS_PRELOAD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_HSTS_PRELOAD
            - name: SECURE_SSL_REDIRECT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_SSL_REDIRECT
            - name: SECURE_PROXY_SSL_HEADER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_PROXY_SSL_HEADER
            - name: X_FRAME_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: X_FRAME_OPTIONS
            - name: SECURE_REFERRER_POLICY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: SECURE_REFERRER_POLICY
            - name: CSRF_COOKIE_SECURE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: CSRF_COOKIE_SECURE
            - name: CSRF_TRUSTED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: CSRF_TRUSTED_ORIGINS
          {{- with .Values.env }}
          # Extra env entries
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: media
              mountPath: /app/media
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: logs
          emptyDir: {}
        - name: media
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}