apiVersion: v1
kind: Namespace
metadata:
  name: opendismissal-demo
  labels:
    name: opendismissal-demo
    app.kubernetes.io/name: opendismissal
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: opendismissal-demo
    environment: demo