apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendismissal-demo

resources:
- ../../base
- configmap.yaml
- secret.yaml
- ingress.yaml
- cert-manager-issuers.yaml
- external-dns-secret.yaml
- external-dns-rbac.yaml
- external-dns-deployment.yaml
- migration-job.yaml
- create-superuser-job.yaml
- generate-demo-data-job.yaml
- demo-data-rbac.yaml

namePrefix: ""
nameSuffix: "-demo"

patches:
- target:
    kind: Namespace
    name: opendismissal
  patch: |-
    - op: replace
      path: /metadata/name
      value: opendismissal-demo
    - op: add
      path: /metadata/labels/environment
      value: demo
- path: web-deployment-patch.yaml
  target:
    kind: Deployment
    name: django
- path: web-image-patch.yaml
  target:
    kind: Deployment
    name: django
- path: web-deployment-env-patch.yaml
  target:
    kind: Deployment
    name: django
- path: web-deployment-redis-patch.yaml
  target:
    kind: Deployment
    name: django
- target:
    kind: Service
    name: postgresql-service
  patch: |-
    - op: replace
      path: /spec/selector
      value:
        app: postgresql
- path: postgresql-statefulset-patch.yaml
  target:
    kind: StatefulSet
    name: postgresql
- path: postgresql-probes-patch.yaml
  target:
    kind: StatefulSet
    name: postgresql
- path: migration-job-patch.yaml
  target:
    kind: Job
    name: django-migrate
- path: create-superuser-job-patch.yaml
  target:
    kind: Job
    name: create-superuser
- path: generate-demo-data-job-patch.yaml
  target:
    kind: Job
    name: generate-demo-data

commonLabels:
  app.kubernetes.io/part-of: opendismissal-demo
  environment: demo