apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  template:
    spec:
      containers:
      - name: django
        env:
        # Add REDIS_URL from configmap
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: REDIS_URL