# Generated by Django 5.2.4 on 2025-08-04 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Full student name", max_length=100)),
                (
                    "dismissal_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique 6-8 character code for parent verification",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("grade", models.CharField(help_text="Student grade level", max_length=20)),
                ("teacher", models.CharField(help_text="Homeroom teacher name", max_length=100)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Active in current dismissal"),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting for Parent"),
                            ("PARENT_ARRIVED", "Parent Has Arrived"),
                            ("PICKED_UP", "Student Picked Up"),
                        ],
                        db_index=True,
                        default="WAITING",
                        help_text="Current dismissal status for quick dashboard queries",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["dismissal_code"], name="dissmissal__dismiss_cd404d_idx"),
                    models.Index(
                        fields=["is_active", "current_status"],
                        name="dissmissal__is_acti_e2a6a1_idx",
                    ),
                    models.Index(fields=["grade", "teacher"], name="dissmissal__grade_23e8b4_idx"),
                    models.Index(fields=["-created_at"], name="dissmissal__created_32530a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PickupEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PARENT_ARRIVED", "Parent Arrived"),
                            ("STUDENT_PICKED_UP", "Student Picked Up"),
                            ("CANCELLED", "Pickup Cancelled"),
                        ],
                        help_text="Type of dismissal event",
                        max_length=20,
                    ),
                ),
                (
                    "dismissal_code_used",
                    models.CharField(
                        help_text="The dismissal code that was used for verification", max_length=8
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="When this event occurred"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional notes about this event"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the staff member when event occurred"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        help_text="Staff member who performed this action",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student this event relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_events",
                        to="dissmissal.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pickup Event",
                "verbose_name_plural": "Pickup Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["student", "-timestamp"], name="dissmissal__student_8da905_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-timestamp"], name="dissmissal__event_t_03997f_idx"
                    ),
                    models.Index(
                        fields=["staff_member", "-timestamp"], name="dissmissal__staff_m_6e9014_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="dissmissal__timesta_a29efb_idx"),
                ],
            },
        ),
    ]
