# Generated by Django 5.2.4 on 2025-08-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissmissal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='dissmissal__current_a9127a_idx',
        ),
    ]
