# Generated by Django 5.2.4 on 2025-08-05 17:24

import dissmissal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissmissal', '0002_remove_student_dissmissal__current_a9127a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dismissal_code',
            field=models.CharField(db_index=True, help_text='3-8 character dismissal code (alphanumeric only)', max_length=8, unique=True, validators=[dissmissal.models.validate_dismissal_code_format]),
        ),
    ]
