# Generated by Django 5.2.4 on 2025-08-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissmissal', '0003_editable_dismissal_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dismissal_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique 1-8 character alphanumeric code for parent verification. Leave blank to auto-generate starting at 100.', max_length=8, unique=True),
        ),
    ]
