apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: opendismissal
  labels:
    app: postgresql
    app.kubernetes.io/name: opendismissal
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: database-service
    app.kubernetes.io/part-of: opendismissal-demo
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP