apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: opendismissal
  labels:
    app: redis
    app.kubernetes.io/name: opendismissal
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: cache-service
    app.kubernetes.io/part-of: opendismissal
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP